modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="minefactoryrenewed"
version="${file.jarVersion}"
displayName="Minefactory Renewed"
#logoFile="logo.png"
credits="Thanks to the original MFR"
authors="abused_master"
description='''
A spiritual renewal of the original MFR
'''

[[dependencies.minefactoryrenewed]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minefactoryrenewed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
